language: python

python:
  - "3.7"

before_script:
  - pip install mkdocs

script:
  - mkdocs build
  
deploy:
  provider: pages
  local-dir: "site"
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
