language: python

python:
  - "3.6"

before_script:
  - pip install mkdocs mkdocs-material

script:
  - mkdocs build
  - ls
  - ls site
  
deploy:
  provider: pages
  local-dir: "site"
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
